spring.application.name=space-marine-backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=12345

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Disable Docker Compose (????? Spring Boot ?? ??????? ????????? ???? ?????????)
spring.docker.compose.enabled=false

# Server
server.port=8080

# Optional: ??? ???????
logging.level.org.springframework=INFO
logging.level.ru.itmo.is=DEBUG

spring.security.filter.order=0

app.jwt.secret=RmFrZVNlY3JldEtleUZvckpXVAo0MzIxMjM0NTY3ODkwMTIzNDU2
app.jwt.expiration=3600000
