spring.application.name=space-marine-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=12345

#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.sql.init.mode=never

spring.docker.compose.enabled=false

server.port=8080

logging.level.org.springframework=INFO
logging.level.ru.itmo.is=DEBUG

spring.security.filter.order=0

app.jwt.secret=RmFrZVNlY3JldEtleUZvckpXVAo0MzIxMjM0NTY3ODkwMTIzNDU2
app.jwt.expiration=3600000


